version: '3'

services:
  app:
    build:
      context: .
    command: tail -f /dev/null
    volumes: 
      - .:/workspace:cached
    links:
      - db
    depends_on:
      - db
    networks:
      - my-network
  
  db:
    image: postgres:latest
    container_name: db-test
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    networks:
      - my-network

networks:
  my-network:
    driver: bridge